import { InteractiveAgentInfo } from '@/types/agent';

export const interactiveAgentsData: InteractiveAgentInfo[] = [
  {
    id: 'inboxzero',
    name: 'InboxZero AI',
    description: 'Reclaim your inbox from chaos. This AI sorts, prioritizes, and responds to routine emails.',
    iconEmoji: '📧',
    demoType: 'inboxZero',
    themeColorClass: 'bg-blue-500',
    longDescription: 'Reclaim your inbox from the clutches of chaos. This AI agent learns your email habits, automatically sorting, prioritizing, and even responding to routine messages. Spend less time managing emails and more time on what matters.',
  },
  {
    id: 'leadspark',
    name: 'LeadSpark AI',
    description: 'Ignite your sales pipeline with intelligent lead generation and qualification.',
    iconEmoji: '🔥',
    demoType: 'leadSpark',
    themeColorClass: 'bg-orange-500',
    longDescription: 'Ignite your sales pipeline with intelligent lead generation. LeadSpark AI scours the web for potential customers, qualifies them based on your criteria, and delivers a steady stream of high-quality leads directly to your CRM.',
  },
  {
    id: 'contentcraft',
    name: 'ContentCraft AI',
    description: 'Unleash your creative potential with an AI that writes, designs, and inspires.',
    iconEmoji: '✍️',
    demoType: 'contentCraft',
    themeColorClass: 'bg-purple-500',
    longDescription: 'Unleash your creative potential with an AI that writes, designs, and inspires. From blog posts and social media updates to marketing copy and website content, ContentCraft AI helps you produce high-quality content at scale.',
  },
  {
    id: 'schedulesync',
    name: 'ScheduleSync AI',
    description: 'Never double-book yourself again. An intelligent assistant for your calendar.',
    iconEmoji: '📅',
    demoType: 'scheduleSync',
    themeColorClass: 'bg-green-500',
    longDescription: 'Never double-book yourself again. This intelligent assistant manages your calendar, scheduling meetings, appointments, and reminders with ease. It even learns your preferences and availability to make scheduling a breeze.',
  },
  {
    id: 'taskmaster',
    name: 'TaskMaster AI',
    description: 'Conquer your to-do list with an AI that organizes, prioritizes, and tracks your tasks.',
    iconEmoji: '✅',
    demoType: 'taskMaster',
    themeColorClass: 'bg-yellow-500',
    longDescription: 'Conquer your to-do list with an AI that organizes, prioritizes, and tracks your tasks. From simple reminders to complex project management, TaskMaster AI keeps you on track and productive.',
  },
  {
    id: 'financetracker',
    name: 'FinanceTracker AI',
    description: 'Take control of your finances with an AI that tracks spending and creates budgets.',
    iconEmoji: '💰',
    demoType: 'financeTracker',
    themeColorClass: 'bg-teal-500',
    longDescription: 'Take control of your finances with an AI that tracks your spending, creates budgets, and provides personalized financial advice. Make smarter financial decisions and achieve your financial goals faster.',
  },
  {
    id: 'shopsmart',
    name: 'ShopSmart AI',
    description: 'Find the best deals on the products you love with an AI-powered shopping assistant.',
    iconEmoji: '🛒',
    demoType: 'shopSmart',
    themeColorClass: 'bg-pink-500',
    longDescription: 'Find the best deals on the products you love. This AI-powered shopping assistant compares prices, finds coupons, and tracks your favorite products to help you save time and money.',
  },
]; 